import { StyleSheet } from "react-native";
import type { lightTheme } from "../../../../theme/themes";

type AppTheme = typeof lightTheme;

export const createProfileStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      backgroundColor: theme.colors.background,
      paddingHorizontal: 16,
      paddingTop: 20,
    },
    handle: {
      width: 40,
      height: 4,
      backgroundColor: theme.colors.muted,
      borderRadius: 2,
      alignSelf: "center",
      marginBottom: 20,
      opacity: 0.6,
    },
    centered: {
      flex: 1,
      backgroundColor: theme.colors.background,
      alignItems: "center",
      justifyContent: "center",
    },
    profileRow: {
      flexDirection: "row",
      alignItems: "center",
    },
    avatarWrapper: {
      marginRight: 20,
    },
    avatar: {
      width: 90,
      height: 90,
      borderRadius: 45,
      borderWidth: 2,
      borderColor: theme.colors.surface,
    },
    infoWrapper: {
      flex: 1,
      justifyContent: "center",
    },
    name: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme.colors.text,
      marginBottom: 0,
    },
    username: {
      fontSize: 16,
      color: theme.colors.accent,
      marginBottom: 8,
      marginLeft: 4,
    },
    badge: {
      position: "absolute",
      top: -8,
      right: -8,
      backgroundColor: theme.colors.primary,
      borderRadius: 10,
      minWidth: 20,
      height: 20,
      alignItems: "center",
      justifyContent: "center",
      borderWidth: 2,
      borderColor: theme.colors.background,
    },
    badgeText: {
      color: theme.colors.text,
      fontSize: 12,
      fontWeight: "bold",
    },
    bio: {
      fontSize: 15,
      color: theme.colors.text,
      textAlign: "left",
    },
    editButton: {
      marginLeft: 8,
      padding: 8,
      borderRadius: 8,
    },
    divider: {
      width: "100%",
      height: 1,
      backgroundColor: theme.colors.separator,
      marginVertical: 24,
      opacity: 1,
    },
    partnerRow: {
      marginBottom: 20,
      marginLeft: 2,
      alignItems: "center",
    },
    partnerText: {
      color: theme.colors.muted,
      fontSize: 15,
      fontWeight: "500",
      textAlign: "center",
    },
    partnerName: {
      color: theme.colors.muted,
      fontWeight: "bold",
    },
    noPartnerName: {
      color: theme.colors.muted,
      fontWeight: "normal",
    },
    modalOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: theme.colors.absoluteFillObject,
      justifyContent: "center",
      alignItems: "center",
    },
    modalContent: {
      marginTop: 120,
      marginHorizontal: 24,
      backgroundColor: theme.colors.background,
      borderRadius: 16,
      padding: 24,
      alignItems: "stretch",
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.2,
      shadowRadius: 10,
      elevation: 5,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "bold",
      color: theme.colors.text,
      marginBottom: 16,
      alignSelf: "center",
    },
    atSymbol: {
      position: "absolute",
      left: 0,
      top: "50%",
      transform: [{ translateY: -10 }],
      color: theme.colors.muted,
      fontSize: 16,
      zIndex: 2,
      paddingLeft: 2,
    },
    inputWithAt: {
      backgroundColor: "transparent",
      color: theme.colors.text,
      borderRadius: 0,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.primary,
      width: "100%",
      fontSize: 16,
      paddingLeft: 18,
      paddingRight: 36,
    },
    editRow: {
      width: "100%",
      marginBottom: 40,
      position: "relative",
      justifyContent: "center",
    },
    input: {
      backgroundColor: "transparent",
      color: theme.colors.text,
      borderRadius: 0,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.primary,
      width: "100%",
      fontSize: 16,
      paddingRight: 36,
    },
    tickIcon: {
      position: "absolute",
      right: 0,
      top: "50%",
      transform: [{ translateY: -11 }],
      zIndex: 2,
    },
    modalButtonRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginTop: 12,
    },
    cancelButton: {
      backgroundColor: theme.colors.primary,
      paddingVertical: 10,
      paddingHorizontal: 24,
      borderRadius: 8,
      alignItems: "center",
      justifyContent: "center",
    },
    cancelButtonText: {
      color: theme.colors.text,
      fontWeight: "bold",
      fontSize: 16,
    },
    toast: {
      position: "absolute",
      bottom: 10,
      left: 20,
      right: 20,
      backgroundColor: theme.colors.primary,
      padding: 14,
      borderRadius: 10,
      alignItems: "center",
      zIndex: 100,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 8,
    },
    toastText: {
      color: theme.colors.text,
      fontWeight: "bold",
      fontSize: 16,
    },
  });
