import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    backgroundColor: "#23243a",
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  centered: {
    flex: 1,
    backgroundColor: "#23243a",
    alignItems: "center",
    justifyContent: "center",
  },
  profileRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarWrapper: {
    marginRight: 20,
  },
  avatar: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderColor: "#e03487",
  },
  infoWrapper: {
    flex: 1,
    justifyContent: "center",
  },
  name: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 0,
  },
  username: {
    fontSize: 16,
    color: "#e03487",
    marginBottom: 8,
    marginLeft: 4,
  },
  badge: {
    position: "absolute",
    top: -8,
    right: -8,
    backgroundColor: "#e03487",
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#23243a",
  },
  badgeText: {
    color: "#fff",
    fontSize: 12,
    fontWeight: "bold",
  },
  bio: {
    fontSize: 15,
    color: "#fff",
    textAlign: "left",
  },
  editButton: {
    marginLeft: 8,
    padding: 8,
    borderRadius: 8,
  },
  divider: {
    width: "100%",
    height: 1,
    backgroundColor: "#393a4a",
    marginVertical: 24,
    opacity: 1,
  },
  partnerRow: {
    marginBottom: 20,
    marginLeft: 2,
    alignItems: "center",
  },
  partnerText: {
    color: "#b0b3c6",
    fontSize: 15,
    fontWeight: "500",
    textAlign: "center",
  },
  partnerName: {
    color: "rgb(155, 158, 180)",
    fontWeight: "bold",
  },
  noPartnerName: {
    color: "rgb(155, 158, 180)",
    fontWeight: "normal",
  },
  modalOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: "rgba(5, 3, 12, 0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    marginTop: 120,
    marginHorizontal: 24,
    backgroundColor: "#23243a",
    borderRadius: 16,
    padding: 24,
    alignItems: "stretch",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 5,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#fff",
    marginBottom: 16,
    alignSelf: "center",
  },
  atSymbol: {
    position: "absolute",
    left: 0,
    top: "50%",
    transform: [{ translateY: -10 }],
    color: "#b0b3c6",
    fontSize: 16,
    zIndex: 2,
    paddingLeft: 2,
  },
  inputWithAt: {
    backgroundColor: "transparent",
    color: "#fff",
    borderRadius: 0,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e03487",
    width: "100%",
    fontSize: 16,
    paddingLeft: 18,
    paddingRight: 36,
  },
  editRow: {
    width: "100%",
    marginBottom: 40,
    position: "relative",
    justifyContent: "center",
  },
  input: {
    backgroundColor: "transparent",
    color: "#fff",
    borderRadius: 0,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#e03487",
    width: "100%",
    fontSize: 16,
    paddingRight: 36,
  },
  tickIcon: {
    position: "absolute",
    right: 0,
    top: "50%",
    transform: [{ translateY: -11 }],
    zIndex: 2,
  },
  modalButtonRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  cancelButton: {
    backgroundColor: "#e03487",
    paddingVertical: 10,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  cancelButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  toast: {
    position: "absolute",
    top: 50,
    // bottom: 40,
    left: 20,
    right: 20,
    backgroundColor: "#e03487",
    padding: 14,
    borderRadius: 10,
    alignItems: "center",
    zIndex: 100,
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 8,
  },
  toastText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
});

export default styles;