import { StyleSheet } from "react-native";
import type { lightTheme } from "../../../../theme/themes";

type AppTheme = typeof lightTheme;

export const createPartnerProfileStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      backgroundColor: theme.colors.background,
      paddingHorizontal: 16,
    },
    portalIcon: {
      position: "absolute",
      top: 16,
      right: 20,
      zIndex: 100,
      backgroundColor: theme.colors.background,
      borderRadius: 20,
      padding: 4,
    },
    profileRow: {
      flexDirection: "row",
      alignItems: "flex-start",
      marginBottom: 16,
      paddingHorizontal: 0,
    },
    avatarWrapper: {
      marginRight: 16,
    },
    avatar: {
      width: 90,
      height: 90,
      borderRadius: 45,
      borderWidth: 2,
      borderColor: theme.colors.surface,
    },
    infoWrapper: {
      flex: 1,
      justifyContent: "flex-start",
      paddingRight: 8,
    },
    name: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme.colors.text,
      marginBottom: 4,
    },
    username: {
      fontSize: 16,
      color: theme.colors.primary,
      marginBottom: 8,
      marginLeft: 0,
    },
    bio: {
      fontSize: 15,
      color: theme.colors.text,
      textAlign: "left",
      marginTop: 4,
    },
    divider: {
      width: "100%",
      height: 1,
      backgroundColor: theme.colors.separator,
      marginVertical: 0,
      opacity: 1,
    },
    partnerRow: {
      marginBottom: 20,
      marginLeft: 20,
      marginRight: 20,
      alignItems: "center",
      marginTop: 20,
      flexDirection: "row",
      justifyContent: "space-between",
    },
    distanceText: {
      fontWeight: "800",
      color: theme.colors.muted,
    },
    apartText: {
      color: theme.colors.muted,
      fontWeight: "500",
    },
    partnerText: {
      color: theme.colors.muted,
      fontSize: 15,
      fontWeight: "500",
      textAlign: "center",
    },
    partnerName: {
      color: theme.colors.muted,
      fontWeight: "bold",
    },
    centered: {
      flex: 1,
      backgroundColor: theme.colors.background,
      alignItems: "center",
      justifyContent: "center",
    },
    removeButtonText: {
      color: theme.colors.text,
      fontWeight: "bold",
      fontSize: 14,
      letterSpacing: 0.5,
    },
    actionButtonsContainer: {
      flexDirection: "row",
      paddingHorizontal: 0,
      paddingVertical: 0,
      marginTop: 0,
      marginBottom: 20,
      gap: 12,
    },
    removeButton: {
      backgroundColor: "#e02222",
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 20,
      alignItems: "center",
      justifyContent: "center",
      flex: 1,
    },
    messageButton: {
      backgroundColor: theme.colors.primary,
      borderRadius: 8,
      paddingVertical: 10,
      paddingHorizontal: 20,
      alignItems: "center",
      justifyContent: "center",
      flex: 1,
      flexDirection: "row",
      gap: 8,
    },
    messageButtonText: {
      color: theme.colors.text,
      fontWeight: "bold",
      fontSize: 14,
      letterSpacing: 0.5,
    },
    toast: {
      position: "absolute",
      bottom: 10,
      left: 20,
      right: 20,
      backgroundColor: theme.colors.primary,
      padding: 14,
      borderRadius: 10,
      alignItems: "center",
      zIndex: 100,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 8,
    },
    toastText: {
      color: theme.colors.text,
      fontWeight: "bold",
      fontSize: 16,
    },
  });
