export type RootStackParamList = {
  Settings: undefined;
  Welcome: undefined;
  Name: undefined;
  Username: undefined;
  Password: undefined;
  Login: undefined;
  Main: undefined;
  ChangeEmail: undefined;
  VerifyEmailOTP: { email?: string } | undefined;
  ChangePassword: undefined;
  PartnerProfile: { userId?: string } | undefined;
  Search: undefined;
  UserProfile: { userId?: string } | undefined;
  PendingRequests: undefined;
  NotesScreen: undefined;
  ChatScreen: { showOptions?: boolean; chatId?: string } | undefined;
  PortalScreen: undefined;
  NotificationsScreen: undefined;
  TimelineScreen: undefined;
  AboutScreen: undefined;
  AllFavoriteMemoriesScreen: undefined;
  SentMessagesScreen: undefined;
  ReceivedMessagesScreen: undefined;
  CartScreen: undefined;
  AccountScreen: undefined;
  GameListScreen: { showOptions?: boolean } | undefined;
  GameWaitingScreen: { roomId?: string } | undefined;
  GameSetupScreen: undefined;
  GameSessionScreen: { sessionId?: string } | undefined;
};
