import { StyleSheet } from "react-native";
import type { lightTheme } from "../../../theme/themes";

type AppTheme = typeof lightTheme;

export const createHomeStyles = (theme: AppTheme) =>
  StyleSheet.create({
    container: {
      backgroundColor: theme.colors.background,
      alignItems: "stretch",
      paddingHorizontal: 16,
    },
    centered: {
      flex: 1,
      backgroundColor: theme.colors.background,
      alignItems: "center",
      justifyContent: "center",
    },
    partnerLabel: {
      fontSize: 14,
      color: theme.colors.muted,
      letterSpacing: 1,
      textTransform: "uppercase",
      marginLeft: 16,
      marginTop: 20,
      marginBottom: 10,
      alignSelf: "flex-start",
    },
    profileCard: {
      backgroundColor: theme.colors.surfaceAlt,
      borderRadius: 20,
      paddingVertical: 20,
      paddingHorizontal: 32,
      alignItems: "flex-start",
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.1,
      shadowRadius: 8,
      elevation: 2,
      width: "100%",
    },
    profileCardInactive: {
      opacity: 0.6,
    },
    profileRow: {
      flexDirection: "row",
      alignItems: "flex-start",
    },
    avatarWrapper: {
      alignSelf: "flex-start",
      marginBottom: 16,
      marginRight: 16,
    },
    avatarContainer: {
      width: 100,
      height: 100,
      position: "relative",
    },
    avatar: {
      width: 100,
      height: 100,
      borderRadius: 50,
      borderWidth: 2,
      borderColor: theme.colors.surface,
    },
    infoWrapper: {
      flex: 1,
      justifyContent: "center",
    },
    name: {
      fontSize: 24,
      fontWeight: "bold",
      color: theme.colors.text,
      marginBottom: 0,
    },
    statusRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      width: "100%",
      marginTop: 10,
    },
    buttonRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      width: "100%",
      paddingHorizontal: 8,
      marginTop: 16,
      marginBottom: 16,
    },
    actionButton: {
      backgroundColor: theme.colors.actionButton,
      borderRadius: 12,
      paddingVertical: 12,
      alignItems: "center",
      width: "100%",
    },
    buttonText: {
      color: theme.colors.text,
      fontSize: 16,
      fontWeight: "bold",
      letterSpacing: 1,
      textTransform: "uppercase",
    },
    blurButton: {
      flex: 1,
      marginHorizontal: 4,
      borderRadius: 12,
      overflow: "hidden",
    },
    upcomingContainer: {
      marginTop: 14,
      width: "100%",
    },
    upcomingLabel: {
      fontSize: 14,
      color: theme.colors.muted,
      letterSpacing: 1,
      textTransform: "uppercase",
      marginBottom: 8,
      marginLeft: 16,
    },
    eventCard: {
      backgroundColor: theme.colors.background,
      borderRadius: 14,
      padding: 18,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 1.5,
    },
    eventName: {
      fontSize: 18,
      fontWeight: "bold",
      color: theme.colors.text,
    },
    eventTimeLeft: {
      fontSize: 14,
      color: theme.colors.muted,
      marginLeft: 8,
      fontWeight: "600",
      opacity: 0.7,
    },
    eventDescription: {
      fontSize: 15,
      color: theme.colors.muted,
      marginTop: 2,
      opacity: 0.85,
    },
    toast: {
      position: "absolute",
      bottom: 10,
      left: 20,
      right: 20,
      backgroundColor: theme.colors.primary,
      padding: 14,
      borderRadius: 10,
      alignItems: "center",
      zIndex: 100,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.2,
      shadowRadius: 8,
      elevation: 8,
    },
    toastText: {
      color: theme.colors.text,
      fontWeight: "bold",
      fontSize: 16,
    },
    absoluteFillObject: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: "rgba(35,36,58,0.7)",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 100,
    },
    interactionCard: {
      backgroundColor: theme.colors.surfaceAlt,
      borderRadius: 16,
      padding: 18,
      marginBottom: 6,
      marginHorizontal: 0,
      position: "relative",
      minHeight: 60,
      shadowColor: theme.colors.shadow,
      shadowOpacity: 0.08,
      shadowRadius: 8,
      elevation: 2,
    },
    interactionCardTitle: {
      color: theme.colors.primary,
      fontWeight: "bold",
      fontSize: 17,
      marginTop: 18,
      marginBottom: 10,
      textAlign: "center",
      letterSpacing: 0.5,
    },
  });
