import { StyleSheet } from "react-native";
import type { lightTheme } from "../../../theme/themes";

type AppTheme = typeof lightTheme;

export const createChatStyles = (theme: AppTheme) =>
  StyleSheet.create({
    header: {
      height: 56,
      justifyContent: "center",
      alignItems: "center",
      backgroundColor: theme.colors.background,
      borderBottomWidth: 1,
      borderBottomColor: theme.colors.surfaceAlt,
      zIndex: 10,
    },
    headerText: {
      color: theme.colors.text,
      fontWeight: "bold",
      fontSize: 20,
      letterSpacing: 1,
      textAlign: "center",
    },
    container: {
      flex: 1,
      backgroundColor: theme.colors.background,
    },
    typingIndicatorWrapper: {
      position: "relative",
      marginBottom: 10,
      alignSelf: "flex-start",
      marginLeft: 12,
    },
    typingIndicatorText: {
      color: theme.colors.muted,
      fontSize: 14,
      fontStyle: "italic",
      marginBottom: 2,
    },
    inputBar: {
      flexDirection: "row",
      alignItems: "center",
      backgroundColor: theme.colors.background,
      paddingHorizontal: 8,
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: theme.colors.border,
    },
    input: {
      flex: 1,
      borderWidth: 1,
      borderColor: theme.colors.border,
      padding: 10,
      borderRadius: 8,
      color: theme.colors.text,
      backgroundColor: theme.colors.surfaceAlt,
      marginRight: 8,
    },
    user: {
      alignSelf: "flex-end",
      backgroundColor: theme.colors.primary,
      color: theme.colors.text,
      padding: 10,
      margin: 4,
      borderRadius: 14,
      maxWidth: "80%",
    },
    bot: {
      alignSelf: "flex-start",
      backgroundColor: theme.colors.surface,
      color: theme.colors.text,
      padding: 10,
      margin: 4,
      marginBottom: 10,
      borderRadius: 14,
      maxWidth: "80%",
    },
    senderLabel: {
      fontSize: 12,
      marginBottom: 2,
      marginLeft: 4,
      marginRight: 4,
      color: theme.colors.muted,
      fontWeight: "500",
    },
    senderLabelUser: {
      alignSelf: "flex-start",
      color: theme.colors.primary,
      marginLeft: 12,
      fontWeight: "bold",
    },
    senderLabelBot: {
      marginLeft: 12,
      alignSelf: "flex-start",
      color: theme.colors.muted,
      fontWeight: "bold",
    },
    sendButton: {
      backgroundColor: theme.colors.primary,
      borderRadius: 8,
      paddingVertical: 9,
      paddingHorizontal: 12,
      marginLeft: 8,
      justifyContent: "center",
      alignItems: "center",
    },
    sendButtonDisabled: {
      backgroundColor: theme.colors.primaryMuted,
      opacity: 0.6,
    },
    sendButtonText: {
      color: theme.colors.text,
      fontWeight: "bold",
      fontSize: 16,
    },
    dayLabelWrapper: {
      alignItems: "center",
      marginVertical: 8,
    },
    dayLabel: {
      backgroundColor: theme.colors.surface,
      color: theme.colors.text,
      paddingHorizontal: 12,
      paddingVertical: 3,
      borderRadius: 12,
      fontSize: 13,
      fontWeight: "bold",
      opacity: 0.85,
    },
    timeLabel: {
      color: theme.colors.muted,
      fontSize: 11,
      marginLeft: 6,
      marginBottom: 10,
      alignSelf: "flex-end",
    },
  });
