import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  header: {
    height: 56,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#23243a",
    borderBottomWidth: 1,
    borderBottomColor: "#393a4a",
    zIndex: 10,
  },
  headerText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 20,
    letterSpacing: 1,
    textAlign: "center",
  },
  container: {
    flex: 1,
    backgroundColor: "#23243a",
  },
  typingIndicatorWrapper: {
    position: "relative",
    marginBottom: 10,
    alignSelf: "flex-start",
    marginLeft: 12,
  },
  typingIndicatorText: {
    color: "#b0b3c6",
    fontSize: 14,
    fontStyle: "italic",
    marginBottom: 2,
  },
  inputBar: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#23243a",
    paddingHorizontal: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: "#393a4a",
  },
  input: {
    flex: 1,
    borderWidth: 1,
    borderColor: "#393a4a",
    padding: 10,
    borderRadius: 8,
    color: "#fff",
    backgroundColor: "#1b1c2e",
    marginRight: 8,
  },
  user: {
    alignSelf: "flex-end",
    backgroundColor: "#e03487",
    color: "#fff",
    padding: 10,
    margin: 4,
    borderRadius: 14,
    maxWidth: "80%",
  },
  bot: {
    alignSelf: "flex-start",
    backgroundColor: "#393a4a",
    color: "#fff",
    padding: 10,
    margin: 4,
    marginBottom: 10,
    borderRadius: 14,
    maxWidth: "80%",
  },
  senderLabel: {
    fontSize: 12,
    marginBottom: 2,
    marginLeft: 4,
    marginRight: 4,
    color: "#b0b3c6",
    fontWeight: "500",
  },
  senderLabelUser: {
    alignSelf: "flex-start",
    color: "#e03487",
    marginLeft: 12,
    fontWeight: "bold",
  },
  senderLabelBot: {
    marginLeft: 12,
    alignSelf: "flex-start",
    color: "#b0b3c6",
    fontWeight: "bold",
  },
  sendButton: {
    backgroundColor: "#e03487",
    borderRadius: 8,
    paddingVertical: 9,
    paddingHorizontal: 12,
    marginLeft: 8,
    justifyContent: "center",
    alignItems: "center",
  },
  sendButtonDisabled: {
    backgroundColor: "#a94c7c",
    opacity: 0.6,
  },
  sendButtonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  dayLabelWrapper: {
    alignItems: "center",
    marginVertical: 8,
  },
  dayLabel: {
    backgroundColor: "#393a4a",
    color: "#fff",
    paddingHorizontal: 12,
    paddingVertical: 3,
    borderRadius: 12,
    fontSize: 13,
    fontWeight: "bold",
    opacity: 0.85,
  },
  timeLabel: {
    color: "#b0b3c6",
    fontSize: 11,
    marginLeft: 6,
    marginBottom: 10,
    alignSelf: "flex-end",
  },
});

export default styles;
